% Universal color set for plot.
% Referenced by
% https://jfly.uni-koeln.de/colorset/CUD_color_set_GuideBook_2018_for_print_cs4.pdf
function rgb = genRGBForPlot(color)
color_table = [
%   255,  75,   0,  1,  "r",  "red"    ;  % 赤
  255,   0,   0,  1,  "r",  "red"    ;  % 赤
%     3, 175, 122,  2,  "g",  "green"  ;  % 緑
    0, 128,   0,  2,  "g",  "green"  ;  % 緑
%     0,  90, 255,  3,  "b",  "blue"   ;  % 青
    0,   0, 255,  3,  "b",  "blue"   ;  % 青
%   153,   0, 153,  4,  "p",  "purple" ;  % 紫
  126,  47, 142,  4,  "p",  "purple" ;  % 紫
  128,  64,   0,  5,  "n",  "brown"  ;  % 茶色
  255, 128, 130,  6,  "m",  "pink"   ;  % ピンク
  246, 170,   0,  7,  "o",  "orange" ;  % オレンジ 
   77, 196, 255,  8,  "c",  "skyblue";  % 空色
%   255, 241,   0,  9,  "y",  "yellow" ;  % 黄色
  237, 176,  33,  9,  "y",  "yellow" ;  % 黄色
    0,   0,   0, 10,  "k",  "black"  ;  % 黒
  129,  41, 144, 11,  "n",  "ngz"    ;  % 乃木坂空色
  222, 125, 178, 12,  "s",  "skz"    ;  % 櫻坂ピンク
   54, 181, 216, 13,  "h",  "hnz"    ;  % 日向坂空色
   94, 185,  84, 14,  "z",  "kyz"    ;  % 欅坂緑色 
  ];

[color_index, ~] = find(color_table(:, 4:end) == string(color));


if isempty(color_index)
  error(append("Color must be selected by the list below." + newline, ...
    "| Number | Symbol |   String   |" + newline, ...
    "|    1   |    r   |      red   |" + newline, ...
    "|    2   |    g   |    green   |" + newline, ...
    "|    3   |    b   |     blue   |" + newline, ...
    "|    4   |    p   |   purple   |" + newline, ...
    "|    5   |    n   |    brown   |" + newline, ...
    "|    6   |    m   |     pink   |" + newline, ...
    "|    7   |    o   |   orange   |" + newline, ...
    "|    8   |    c   |  skyblue   |" + newline, ...
    "|    9   |    y   |   yellow   |" + newline, ...
    "|   10   |    k   |    black   |" + newline,  ...
    "|   11   |    n   |      ngz   |" + newline,  ...
    "|   12   |    s   |      skz   |" + newline,  ...
    "|   13   |    h   |      hnz   |" + newline,  ...
    "|   14   |    z   |      kyz   |" + newline  ...
    ))
end
rgb = double(color_table(color_index, 1:3))/255;
end
